# Generated by Django 5.0.1 on 2024-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
