# Generated by Django 5.0.1 on 2024-05-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_groupchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='name',
            new_name='group_name',
        ),
    ]
