# Generated by Django 5.0.1 on 2024-05-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog.groupchat'),
        ),
    ]
