# Generated by Django 5.0.1 on 2024-05-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_groupchat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_pictures/'),
        ),
    ]
